repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.1
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix    ]
        additional_dependencies: [ ruff==0.6.1 ]
